spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    hikari:
      connection-timeout: 10000
      validation-timeout: 10000
      maximum-pool-size: 15
    driver-class-name: org.hibernate.dialect.MySQL5InnoDBDialect
    url: jdbc:mysql://localhost:3306/ffmanager?useSSL=false
    username: root
    password: admin1234
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: false

server:
  servlet:
    context-path: /servicios

logging:
#  config: ./config/logback.xml
  level:
    org:
      springframework:
        web: INFO
      hibernate:
        engine:
          jdbc:
            spi:
              SqlExceptionHelper: ERROR
    
      com:
        mucam: TRACE

