spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    hikari:
      connection-timeout: 10000
      validation-timeout: 10000
      maximum-pool-size: 15
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    url: jdbc:db2://t-db:50001/desa
    username: rbermude
    password: RBERMUDEZ
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    show-sql: false

server:
  servlet:
    context-path: /servicios

logging:
#  config: ./config/logback.xml
  level:
    org:
      springframework:
        web: INFO
      hibernate:
        engine:
          jdbc:
            spi:
              SqlExceptionHelper: ERROR
    
      com:
        mucam: TRACE

